# Generated by Django 3.2.12 on 2023-12-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('group', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=128)),
                ('teacher', models.CharField(max_length=256)),
                ('lecture_hall', models.IntegerField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='lections_images')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lections.specialization')),
            ],
        ),
    ]
